/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTutorRouteImport } from './routes/_app/tutor'
import { Route as AppRetosRouteImport } from './routes/_app/retos'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppLogrosRouteImport } from './routes/_app/logros'
import { Route as AppInicioRouteImport } from './routes/_app/inicio'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCursosRouteImport } from './routes/_app/cursos'
import { Route as AppLeccionIdRouteImport } from './routes/_app/leccion.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppRetosRoute = AppRetosRouteImport.update({
  id: '/retos',
  path: '/retos',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppLogrosRoute = AppLogrosRouteImport.update({
  id: '/logros',
  path: '/logros',
  getParentRoute: () => AppRoute,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCursosRoute = AppCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AppRoute,
} as any)
const AppLeccionIdRoute = AppLeccionIdRouteImport.update({
  id: '/leccion/$id',
  path: '/leccion/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/cursos': typeof AppCursosRoute
  '/dashboard': typeof AppDashboardRoute
  '/inicio': typeof AppInicioRoute
  '/logros': typeof AppLogrosRoute
  '/perfil': typeof AppPerfilRoute
  '/retos': typeof AppRetosRoute
  '/tutor': typeof AppTutorRoute
  '/leccion/$id': typeof AppLeccionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/cursos': typeof AppCursosRoute
  '/dashboard': typeof AppDashboardRoute
  '/inicio': typeof AppInicioRoute
  '/logros': typeof AppLogrosRoute
  '/perfil': typeof AppPerfilRoute
  '/retos': typeof AppRetosRoute
  '/tutor': typeof AppTutorRoute
  '/leccion/$id': typeof AppLeccionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/cursos': typeof AppCursosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inicio': typeof AppInicioRoute
  '/_app/logros': typeof AppLogrosRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/retos': typeof AppRetosRoute
  '/_app/tutor': typeof AppTutorRoute
  '/_app/leccion/$id': typeof AppLeccionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/cursos'
    | '/dashboard'
    | '/inicio'
    | '/logros'
    | '/perfil'
    | '/retos'
    | '/tutor'
    | '/leccion/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/cursos'
    | '/dashboard'
    | '/inicio'
    | '/logros'
    | '/perfil'
    | '/retos'
    | '/tutor'
    | '/leccion/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/cursos'
    | '/_app/dashboard'
    | '/_app/inicio'
    | '/_app/logros'
    | '/_app/perfil'
    | '/_app/retos'
    | '/_app/tutor'
    | '/_app/leccion/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tutor': {
      id: '/_app/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/retos': {
      id: '/_app/retos'
      path: '/retos'
      fullPath: '/retos'
      preLoaderRoute: typeof AppRetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logros': {
      id: '/_app/logros'
      path: '/logros'
      fullPath: '/logros'
      preLoaderRoute: typeof AppLogrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inicio': {
      id: '/_app/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cursos': {
      id: '/_app/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof AppCursosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leccion/$id': {
      id: '/_app/leccion/$id'
      path: '/leccion/$id'
      fullPath: '/leccion/$id'
      preLoaderRoute: typeof AppLeccionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCursosRoute: typeof AppCursosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInicioRoute: typeof AppInicioRoute
  AppLogrosRoute: typeof AppLogrosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRetosRoute: typeof AppRetosRoute
  AppTutorRoute: typeof AppTutorRoute
  AppLeccionIdRoute: typeof AppLeccionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCursosRoute: AppCursosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInicioRoute: AppInicioRoute,
  AppLogrosRoute: AppLogrosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRetosRoute: AppRetosRoute,
  AppTutorRoute: AppTutorRoute,
  AppLeccionIdRoute: AppLeccionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
